### ISSUE TITLE
Multi-site support

### ISSUE THREAD

**Issue by TomDeSmet** [nystudio107/rollup-plugin-critical#3]
Would it be possible to have the `criticalUrl` property accept an array of URL's that calls `critical.generate()` multiple times and have the resulting files prefixed with the second level domain of the URL? This way we can have multi-site support I think.

**Comment by development-lameco** [comment]
I'm wondering how one would go about setting this plugin up with a multi-site Craft CMS.

Because in the config you set a `criticalUrl` and `criticalPages` with an URI to an existing URL belonging to an entry in the Craft CMS with a _changeable slug_. What if the _slug_ of the entry changes, you would have to change to URI in the `criticalPages` to match the new URL. Else how would `{{ craft.vite.includeCriticalCssTags() }}` know to output the previously generated Critical CSS?

**Comment by khalwat** [comment]
If you have special needs, I'd suggest writing a script that calls `critical` directly; probably this Vite plugin isn't going to do what you need.
